# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Citas_Admi.ui'
##
## Created by: Qt User Interface Compiler version 6.7.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDateTimeEdit, QLabel,
    QLineEdit, QMainWindow, QMenuBar, QPushButton,
    QSizePolicy, QStatusBar, QWidget)

class Ui_Citas_Admi(object):
    def setupUi(self, Citas_Admi):
        if not Citas_Admi.objectName():
            Citas_Admi.setObjectName(u"Citas_Admi")
        Citas_Admi.resize(910, 638)
        Citas_Admi.setAutoFillBackground(False)
        Citas_Admi.setStyleSheet(u"QWidget#centralwidget{\n"
"background-color:rgb(104, 173, 181)}")
        self.centralwidget = QWidget(Citas_Admi)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(50, 0, 411, 91))
        palette = QPalette()
        brush = QBrush(QColor(229, 229, 229, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        self.label.setPalette(palette)
        font = QFont()
        font.setFamilies([u"Cascadia Code"])
        font.setPointSize(20)
        font.setBold(True)
        self.label.setFont(font)
        self.Sede_2 = QLabel(self.centralwidget)
        self.Sede_2.setObjectName(u"Sede_2")
        self.Sede_2.setGeometry(QRect(90, 140, 291, 20))
        palette1 = QPalette()
        brush1 = QBrush(QColor(235, 235, 235, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        brush2 = QBrush(QColor(235, 253, 255, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        self.Sede_2.setPalette(palette1)
        font1 = QFont()
        font1.setFamilies([u"Cascadia Code"])
        font1.setPointSize(16)
        font1.setBold(True)
        self.Sede_2.setFont(font1)
        self.Sede = QComboBox(self.centralwidget)
        icon = QIcon(QIcon.fromTheme(u"accessories-character-map"))
        self.Sede.addItem(icon, "")
        self.Sede.addItem("")
        self.Sede.addItem("")
        self.Sede.addItem("")
        self.Sede.setObjectName(u"Sede")
        self.Sede.setGeometry(QRect(110, 180, 211, 28))
        palette2 = QPalette()
        brush3 = QBrush(QColor(255, 255, 255, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush3)
        brush4 = QBrush(QColor(103, 153, 158, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.Button, brush4)
        palette2.setBrush(QPalette.Active, QPalette.Text, brush3)
        palette2.setBrush(QPalette.Active, QPalette.ButtonText, brush3)
        palette2.setBrush(QPalette.Active, QPalette.Base, brush4)
        palette2.setBrush(QPalette.Active, QPalette.Window, brush4)
        brush5 = QBrush(QColor(255, 255, 255, 128))
        brush5.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Active, QPalette.PlaceholderText, brush5)
#endif
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush3)
        palette2.setBrush(QPalette.Inactive, QPalette.Button, brush4)
        palette2.setBrush(QPalette.Inactive, QPalette.Text, brush3)
        palette2.setBrush(QPalette.Inactive, QPalette.ButtonText, brush3)
        palette2.setBrush(QPalette.Inactive, QPalette.Base, brush4)
        palette2.setBrush(QPalette.Inactive, QPalette.Window, brush4)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush5)
#endif
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush3)
        palette2.setBrush(QPalette.Disabled, QPalette.Button, brush4)
        palette2.setBrush(QPalette.Disabled, QPalette.Text, brush3)
        palette2.setBrush(QPalette.Disabled, QPalette.ButtonText, brush3)
        palette2.setBrush(QPalette.Disabled, QPalette.Base, brush4)
        palette2.setBrush(QPalette.Disabled, QPalette.Window, brush4)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush5)
#endif
        self.Sede.setPalette(palette2)
        self.Sede.setStyleSheet(u"border-radius:20px;\n"
"background-color: rgb(103, 153, 158);\n"
"font: 14pt \"Cascadia Code\";\n"
"color: white;")
        self.Cliente = QLabel(self.centralwidget)
        self.Cliente.setObjectName(u"Cliente")
        self.Cliente.setGeometry(QRect(80, 240, 321, 20))
        palette3 = QPalette()
        brush6 = QBrush(QColor(236, 236, 236, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush6)
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush6)
        self.Cliente.setPalette(palette3)
        self.Cliente.setFont(font1)
        self.NombreCliente = QLineEdit(self.centralwidget)
        self.NombreCliente.setObjectName(u"NombreCliente")
        self.NombreCliente.setGeometry(QRect(60, 280, 341, 51))
        palette4 = QPalette()
        palette4.setBrush(QPalette.Active, QPalette.WindowText, brush3)
        palette4.setBrush(QPalette.Active, QPalette.Button, brush4)
        palette4.setBrush(QPalette.Active, QPalette.Text, brush3)
        palette4.setBrush(QPalette.Active, QPalette.ButtonText, brush3)
        palette4.setBrush(QPalette.Active, QPalette.Base, brush4)
        palette4.setBrush(QPalette.Active, QPalette.Window, brush4)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.Active, QPalette.PlaceholderText, brush5)
#endif
        palette4.setBrush(QPalette.Inactive, QPalette.WindowText, brush3)
        palette4.setBrush(QPalette.Inactive, QPalette.Button, brush4)
        palette4.setBrush(QPalette.Inactive, QPalette.Text, brush3)
        palette4.setBrush(QPalette.Inactive, QPalette.ButtonText, brush3)
        palette4.setBrush(QPalette.Inactive, QPalette.Base, brush4)
        palette4.setBrush(QPalette.Inactive, QPalette.Window, brush4)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush5)
#endif
        palette4.setBrush(QPalette.Disabled, QPalette.WindowText, brush3)
        palette4.setBrush(QPalette.Disabled, QPalette.Button, brush4)
        palette4.setBrush(QPalette.Disabled, QPalette.Text, brush3)
        palette4.setBrush(QPalette.Disabled, QPalette.ButtonText, brush3)
        palette4.setBrush(QPalette.Disabled, QPalette.Base, brush4)
        palette4.setBrush(QPalette.Disabled, QPalette.Window, brush4)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush5)
#endif
        self.NombreCliente.setPalette(palette4)
        self.NombreCliente.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.NombreCliente.setContextMenuPolicy(Qt.ContextMenuPolicy.DefaultContextMenu)
        self.NombreCliente.setStyleSheet(u"border-radius:20px;\n"
"background-color: rgb(103, 153, 158);\n"
"font: 14pt \"Cascadia Code\";\n"
"color: white;")
        self.Correo_2 = QLabel(self.centralwidget)
        self.Correo_2.setObjectName(u"Correo_2")
        self.Correo_2.setGeometry(QRect(80, 360, 321, 21))
        palette5 = QPalette()
        palette5.setBrush(QPalette.Active, QPalette.WindowText, brush6)
        palette5.setBrush(QPalette.Inactive, QPalette.WindowText, brush6)
        self.Correo_2.setPalette(palette5)
        self.Correo_2.setFont(font1)
        self.Correo = QLineEdit(self.centralwidget)
        self.Correo.setObjectName(u"Correo")
        self.Correo.setGeometry(QRect(60, 410, 341, 51))
        palette6 = QPalette()
        brush7 = QBrush(QColor(0, 0, 0, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette6.setBrush(QPalette.Active, QPalette.WindowText, brush7)
        palette6.setBrush(QPalette.Active, QPalette.Button, brush4)
        brush8 = QBrush(QColor(204, 250, 255, 255))
        brush8.setStyle(Qt.SolidPattern)
        palette6.setBrush(QPalette.Active, QPalette.Light, brush8)
        brush9 = QBrush(QColor(168, 213, 218, 255))
        brush9.setStyle(Qt.SolidPattern)
        palette6.setBrush(QPalette.Active, QPalette.Midlight, brush9)
        brush10 = QBrush(QColor(66, 88, 90, 255))
        brush10.setStyle(Qt.SolidPattern)
        palette6.setBrush(QPalette.Active, QPalette.Dark, brush10)
        brush11 = QBrush(QColor(89, 117, 121, 255))
        brush11.setStyle(Qt.SolidPattern)
        palette6.setBrush(QPalette.Active, QPalette.Mid, brush11)
        palette6.setBrush(QPalette.Active, QPalette.Text, brush7)
        brush12 = QBrush(QColor(174, 255, 228, 255))
        brush12.setStyle(Qt.SolidPattern)
        palette6.setBrush(QPalette.Active, QPalette.BrightText, brush12)
        palette6.setBrush(QPalette.Active, QPalette.ButtonText, brush7)
        palette6.setBrush(QPalette.Active, QPalette.Base, brush4)
        palette6.setBrush(QPalette.Active, QPalette.Window, brush4)
        palette6.setBrush(QPalette.Active, QPalette.Shadow, brush7)
        brush13 = QBrush(QColor(194, 215, 218, 255))
        brush13.setStyle(Qt.SolidPattern)
        palette6.setBrush(QPalette.Active, QPalette.AlternateBase, brush13)
        brush14 = QBrush(QColor(255, 255, 220, 255))
        brush14.setStyle(Qt.SolidPattern)
        palette6.setBrush(QPalette.Active, QPalette.ToolTipBase, brush14)
        palette6.setBrush(QPalette.Active, QPalette.ToolTipText, brush7)
        brush15 = QBrush(QColor(0, 0, 0, 127))
        brush15.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette6.setBrush(QPalette.Active, QPalette.PlaceholderText, brush15)
#endif
        palette6.setBrush(QPalette.Active, QPalette.Accent, brush3)
        palette6.setBrush(QPalette.Inactive, QPalette.WindowText, brush7)
        palette6.setBrush(QPalette.Inactive, QPalette.Button, brush4)
        palette6.setBrush(QPalette.Inactive, QPalette.Light, brush8)
        palette6.setBrush(QPalette.Inactive, QPalette.Midlight, brush9)
        palette6.setBrush(QPalette.Inactive, QPalette.Dark, brush10)
        palette6.setBrush(QPalette.Inactive, QPalette.Mid, brush11)
        palette6.setBrush(QPalette.Inactive, QPalette.Text, brush7)
        palette6.setBrush(QPalette.Inactive, QPalette.BrightText, brush12)
        palette6.setBrush(QPalette.Inactive, QPalette.ButtonText, brush7)
        palette6.setBrush(QPalette.Inactive, QPalette.Base, brush4)
        palette6.setBrush(QPalette.Inactive, QPalette.Window, brush4)
        palette6.setBrush(QPalette.Inactive, QPalette.Shadow, brush7)
        palette6.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush13)
        palette6.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush14)
        palette6.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush7)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette6.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush15)
#endif
        palette6.setBrush(QPalette.Inactive, QPalette.Accent, brush3)
        palette6.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        palette6.setBrush(QPalette.Disabled, QPalette.Button, brush4)
        palette6.setBrush(QPalette.Disabled, QPalette.Light, brush8)
        palette6.setBrush(QPalette.Disabled, QPalette.Midlight, brush9)
        palette6.setBrush(QPalette.Disabled, QPalette.Dark, brush10)
        palette6.setBrush(QPalette.Disabled, QPalette.Mid, brush11)
        palette6.setBrush(QPalette.Disabled, QPalette.Text, brush10)
        palette6.setBrush(QPalette.Disabled, QPalette.BrightText, brush12)
        palette6.setBrush(QPalette.Disabled, QPalette.ButtonText, brush10)
        palette6.setBrush(QPalette.Disabled, QPalette.Base, brush4)
        palette6.setBrush(QPalette.Disabled, QPalette.Window, brush4)
        palette6.setBrush(QPalette.Disabled, QPalette.Shadow, brush7)
        brush16 = QBrush(QColor(133, 176, 181, 255))
        brush16.setStyle(Qt.SolidPattern)
        palette6.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush16)
        palette6.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush14)
        palette6.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush7)
        brush17 = QBrush(QColor(66, 88, 90, 127))
        brush17.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette6.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush17)
#endif
        brush18 = QBrush(QColor(173, 229, 235, 255))
        brush18.setStyle(Qt.SolidPattern)
        palette6.setBrush(QPalette.Disabled, QPalette.Accent, brush18)
        self.Correo.setPalette(palette6)
        self.Correo.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.Correo.setContextMenuPolicy(Qt.ContextMenuPolicy.DefaultContextMenu)
        self.Correo.setStyleSheet(u"border-radius:20px;\n"
"background-color: rgb(103, 153, 158);\n"
"font: 14pt \"Cascadia Code\";\n"
"color: white;")
        self.Horario = QLabel(self.centralwidget)
        self.Horario.setObjectName(u"Horario")
        self.Horario.setGeometry(QRect(520, 200, 291, 20))
        palette7 = QPalette()
        palette7.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette7.setBrush(QPalette.Active, QPalette.Text, brush2)
        palette7.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette7.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        self.Horario.setPalette(palette7)
        self.Horario.setFont(font1)
        self.dateTimeEdit = QDateTimeEdit(self.centralwidget)
        self.dateTimeEdit.setObjectName(u"dateTimeEdit")
        self.dateTimeEdit.setGeometry(QRect(530, 240, 271, 61))
        palette8 = QPalette()
        palette8.setBrush(QPalette.Active, QPalette.WindowText, brush3)
        palette8.setBrush(QPalette.Active, QPalette.Button, brush4)
        palette8.setBrush(QPalette.Active, QPalette.Text, brush3)
        palette8.setBrush(QPalette.Active, QPalette.ButtonText, brush3)
        palette8.setBrush(QPalette.Active, QPalette.Base, brush4)
        palette8.setBrush(QPalette.Active, QPalette.Window, brush4)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette8.setBrush(QPalette.Active, QPalette.PlaceholderText, brush5)
#endif
        palette8.setBrush(QPalette.Inactive, QPalette.WindowText, brush3)
        palette8.setBrush(QPalette.Inactive, QPalette.Button, brush4)
        palette8.setBrush(QPalette.Inactive, QPalette.Text, brush3)
        palette8.setBrush(QPalette.Inactive, QPalette.ButtonText, brush3)
        palette8.setBrush(QPalette.Inactive, QPalette.Base, brush4)
        palette8.setBrush(QPalette.Inactive, QPalette.Window, brush4)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette8.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush5)
#endif
        palette8.setBrush(QPalette.Disabled, QPalette.WindowText, brush3)
        palette8.setBrush(QPalette.Disabled, QPalette.Button, brush4)
        palette8.setBrush(QPalette.Disabled, QPalette.Text, brush3)
        palette8.setBrush(QPalette.Disabled, QPalette.ButtonText, brush3)
        palette8.setBrush(QPalette.Disabled, QPalette.Base, brush4)
        palette8.setBrush(QPalette.Disabled, QPalette.Window, brush4)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette8.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush5)
#endif
        self.dateTimeEdit.setPalette(palette8)
        font2 = QFont()
        font2.setFamilies([u"Cascadia Code"])
        font2.setPointSize(14)
        font2.setBold(False)
        font2.setItalic(False)
        self.dateTimeEdit.setFont(font2)
        self.dateTimeEdit.setStyleSheet(u"border-radius:20px;\n"
"background-color: rgb(103, 153, 158);\n"
"font: 14pt \"Cascadia Code\";\n"
"color: white;")
        self.dateTimeEdit.setTime(QTime(0, 0, 0))
        self.dateTimeEdit.setMinimumDate(QDate(2020, 1, 1))
        self.Confirmacion = QPushButton(self.centralwidget)
        self.Confirmacion.setObjectName(u"Confirmacion")
        self.Confirmacion.setGeometry(QRect(520, 380, 301, 61))
        palette9 = QPalette()
        palette9.setBrush(QPalette.Active, QPalette.WindowText, brush3)
        palette9.setBrush(QPalette.Active, QPalette.Button, brush4)
        palette9.setBrush(QPalette.Active, QPalette.Text, brush3)
        palette9.setBrush(QPalette.Active, QPalette.ButtonText, brush3)
        palette9.setBrush(QPalette.Active, QPalette.Base, brush4)
        palette9.setBrush(QPalette.Active, QPalette.Window, brush4)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette9.setBrush(QPalette.Active, QPalette.PlaceholderText, brush5)
#endif
        palette9.setBrush(QPalette.Inactive, QPalette.WindowText, brush3)
        palette9.setBrush(QPalette.Inactive, QPalette.Button, brush4)
        palette9.setBrush(QPalette.Inactive, QPalette.Text, brush3)
        palette9.setBrush(QPalette.Inactive, QPalette.ButtonText, brush3)
        palette9.setBrush(QPalette.Inactive, QPalette.Base, brush4)
        palette9.setBrush(QPalette.Inactive, QPalette.Window, brush4)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette9.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush5)
#endif
        palette9.setBrush(QPalette.Disabled, QPalette.WindowText, brush3)
        palette9.setBrush(QPalette.Disabled, QPalette.Button, brush4)
        palette9.setBrush(QPalette.Disabled, QPalette.Text, brush3)
        palette9.setBrush(QPalette.Disabled, QPalette.ButtonText, brush3)
        palette9.setBrush(QPalette.Disabled, QPalette.Base, brush4)
        palette9.setBrush(QPalette.Disabled, QPalette.Window, brush4)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette9.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush5)
#endif
        self.Confirmacion.setPalette(palette9)
        self.Confirmacion.setFont(font2)
        self.Confirmacion.setStyleSheet(u"border-radius:20px;\n"
"background-color: rgb(103, 153, 158);\n"
"font: 14pt \"Cascadia Code\";\n"
"color: white;")
        self.Confirmacion.setCheckable(False)
        self.Confirmacion.setAutoDefault(False)
        self.Salir = QPushButton(self.centralwidget)
        self.Salir.setObjectName(u"Salir")
        self.Salir.setGeometry(QRect(660, 510, 211, 51))
        palette10 = QPalette()
        palette10.setBrush(QPalette.Active, QPalette.WindowText, brush3)
        palette10.setBrush(QPalette.Active, QPalette.Button, brush4)
        palette10.setBrush(QPalette.Active, QPalette.Text, brush3)
        palette10.setBrush(QPalette.Active, QPalette.ButtonText, brush3)
        palette10.setBrush(QPalette.Active, QPalette.Base, brush4)
        palette10.setBrush(QPalette.Active, QPalette.Window, brush4)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette10.setBrush(QPalette.Active, QPalette.PlaceholderText, brush5)
#endif
        palette10.setBrush(QPalette.Inactive, QPalette.WindowText, brush3)
        palette10.setBrush(QPalette.Inactive, QPalette.Button, brush4)
        palette10.setBrush(QPalette.Inactive, QPalette.Text, brush3)
        palette10.setBrush(QPalette.Inactive, QPalette.ButtonText, brush3)
        palette10.setBrush(QPalette.Inactive, QPalette.Base, brush4)
        palette10.setBrush(QPalette.Inactive, QPalette.Window, brush4)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette10.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush5)
#endif
        palette10.setBrush(QPalette.Disabled, QPalette.WindowText, brush3)
        palette10.setBrush(QPalette.Disabled, QPalette.Button, brush4)
        palette10.setBrush(QPalette.Disabled, QPalette.Text, brush3)
        palette10.setBrush(QPalette.Disabled, QPalette.ButtonText, brush3)
        palette10.setBrush(QPalette.Disabled, QPalette.Base, brush4)
        palette10.setBrush(QPalette.Disabled, QPalette.Window, brush4)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette10.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush5)
#endif
        self.Salir.setPalette(palette10)
        self.Salir.setFont(font2)
        self.Salir.setStyleSheet(u"border-radius:20px;\n"
"background-color: rgb(103, 153, 158);\n"
"font: 14pt \"Cascadia Code\";\n"
"color: white;")
        self.Salir.setCheckable(False)
        self.Salir.setAutoDefault(False)
        Citas_Admi.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(Citas_Admi)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 910, 33))
        Citas_Admi.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(Citas_Admi)
        self.statusbar.setObjectName(u"statusbar")
        Citas_Admi.setStatusBar(self.statusbar)

        self.retranslateUi(Citas_Admi)

        QMetaObject.connectSlotsByName(Citas_Admi)
    # setupUi

    def retranslateUi(self, Citas_Admi):
        Citas_Admi.setWindowTitle(QCoreApplication.translate("Citas_Admi", u"MainWindow", None))
        self.label.setText(QCoreApplication.translate("Citas_Admi", u"Formulario de Citas", None))
        self.Sede_2.setText(QCoreApplication.translate("Citas_Admi", u"Seleccionar Sede", None))
        self.Sede.setItemText(0, "")
        self.Sede.setItemText(1, QCoreApplication.translate("Citas_Admi", u"Sede 1", None))
        self.Sede.setItemText(2, QCoreApplication.translate("Citas_Admi", u"Sede 2", None))
        self.Sede.setItemText(3, QCoreApplication.translate("Citas_Admi", u"Sede 3", None))

        self.Cliente.setText(QCoreApplication.translate("Citas_Admi", u"Nombre del Cliente", None))
        self.NombreCliente.setText("")
        self.Correo_2.setText(QCoreApplication.translate("Citas_Admi", u"Correo electronico ", None))
        self.Correo.setText("")
        self.Horario.setText(QCoreApplication.translate("Citas_Admi", u"Horario disponible", None))
        self.Confirmacion.setText(QCoreApplication.translate("Citas_Admi", u"Enviar Confirmaci\u00f3n", None))
        self.Salir.setText(QCoreApplication.translate("Citas_Admi", u"Salir", None))
    # retranslateUi

