# Form implementation generated from reading ui file 'c:\Datos1_Proyecto1\MyPetsCR\Interfaz\Citas_Admi.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(910, 638)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("rgb(211, 213, 181)")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Light")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(50, 80, 221, 51))
        self.label_5.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.comboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(290, 100, 171, 21))
        self.comboBox.setStyleSheet("border-radius:5px;")
        self.comboBox.setObjectName("comboBox")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 130, 241, 41))
        self.label_3.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 180, 241, 41))
        self.label_4.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(40, 260, 241, 41))
        self.label_6.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_6")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(290, 130, 381, 41))
        self.lineEdit.setStyleSheet("border-radius:10px;")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(290, 180, 381, 41))
        self.lineEdit_2.setStyleSheet("border-radius:10px;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.timeEdit = QtWidgets.QTimeEdit(parent=self.centralwidget)
        self.timeEdit.setGeometry(QtCore.QRect(290, 270, 321, 31))
        self.timeEdit.setObjectName("timeEdit")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(40, 300, 241, 41))
        self.label_7.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.label_7.setObjectName("label_7")
        self.dateEdit = QtWidgets.QDateEdit(parent=self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(290, 310, 321, 31))
        self.dateEdit.setObjectName("dateEdit")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(400, 500, 301, 51))
        self.pushButton.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(170, 0, 255);\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"color: white;")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(730, 500, 151, 51))
        self.pushButton_2.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(170, 0, 255);\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"color: white;")
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 910, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Agendar Cita"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Sede:</p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Cliente:</p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Correo:</p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Hora:</p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Fecha:</p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Enviar Confirmación"))
        self.pushButton_2.setText(_translate("MainWindow", "Salir "))
