# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Citas_Admi.ui'
##
## Created by: Qt User Interface Compiler version 6.7.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDateTimeEdit, QLabel,
    QLineEdit, QMainWindow, QMenuBar, QPushButton,
    QSizePolicy, QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 590)
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush)
        brush1 = QBrush(QColor(88, 191, 211, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        MainWindow.setPalette(palette)
        MainWindow.setAnimated(True)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 10, 371, 71))
        palette1 = QPalette()
        brush2 = QBrush(QColor(253, 253, 253, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush2)
        palette1.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        brush3 = QBrush(QColor(120, 120, 120, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush3)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush3)
        palette1.setBrush(QPalette.Disabled, QPalette.ButtonText, brush3)
        self.label.setPalette(palette1)
        font = QFont()
        font.setFamilies([u"Century Gothic"])
        font.setPointSize(18)
        font.setBold(False)
        self.label.setFont(font)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(50, 110, 241, 71))
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette2.setBrush(QPalette.Active, QPalette.Text, brush2)
        palette2.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette2.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        palette2.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush3)
        palette2.setBrush(QPalette.Disabled, QPalette.Text, brush3)
        palette2.setBrush(QPalette.Disabled, QPalette.ButtonText, brush3)
        self.label_2.setPalette(palette2)
        font1 = QFont()
        font1.setFamilies([u"Century Gothic"])
        font1.setPointSize(14)
        font1.setBold(False)
        self.label_2.setFont(font1)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(420, 150, 241, 71))
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette3.setBrush(QPalette.Active, QPalette.Text, brush2)
        palette3.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette3.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        palette3.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.WindowText, brush3)
        palette3.setBrush(QPalette.Disabled, QPalette.Text, brush3)
        palette3.setBrush(QPalette.Disabled, QPalette.ButtonText, brush3)
        self.label_3.setPalette(palette3)
        self.label_3.setFont(font1)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(40, 230, 241, 71))
        palette4 = QPalette()
        palette4.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette4.setBrush(QPalette.Active, QPalette.Text, brush2)
        palette4.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette4.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        palette4.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette4.setBrush(QPalette.Disabled, QPalette.WindowText, brush3)
        palette4.setBrush(QPalette.Disabled, QPalette.Text, brush3)
        palette4.setBrush(QPalette.Disabled, QPalette.ButtonText, brush3)
        self.label_4.setPalette(palette4)
        self.label_4.setFont(font1)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(40, 330, 241, 71))
        palette5 = QPalette()
        palette5.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette5.setBrush(QPalette.Active, QPalette.Text, brush2)
        palette5.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette5.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        palette5.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette5.setBrush(QPalette.Disabled, QPalette.WindowText, brush3)
        palette5.setBrush(QPalette.Disabled, QPalette.Text, brush3)
        palette5.setBrush(QPalette.Disabled, QPalette.ButtonText, brush3)
        self.label_5.setPalette(palette5)
        self.label_5.setFont(font1)
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(500, 380, 131, 41))
        font2 = QFont()
        font2.setFamilies([u"Century Gothic"])
        font2.setPointSize(10)
        font2.setBold(True)
        self.pushButton.setFont(font2)
        self.sede = QComboBox(self.centralwidget)
        self.sede.setObjectName(u"sede")
        self.sede.setGeometry(QRect(50, 180, 251, 41))
        palette6 = QPalette()
        brush4 = QBrush(QColor(0, 0, 0, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette6.setBrush(QPalette.Active, QPalette.WindowText, brush4)
        brush5 = QBrush(QColor(9, 9, 9, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette6.setBrush(QPalette.Active, QPalette.Light, brush5)
        brush6 = QBrush(QColor(4, 6, 7, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette6.setBrush(QPalette.Active, QPalette.Dark, brush6)
        palette6.setBrush(QPalette.Active, QPalette.Text, brush4)
        palette6.setBrush(QPalette.Active, QPalette.BrightText, brush4)
        palette6.setBrush(QPalette.Active, QPalette.ButtonText, brush4)
        brush7 = QBrush(QColor(81, 151, 184, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette6.setBrush(QPalette.Active, QPalette.Base, brush7)
        brush8 = QBrush(QColor(2, 2, 2, 255))
        brush8.setStyle(Qt.SolidPattern)
        palette6.setBrush(QPalette.Active, QPalette.HighlightedText, brush8)
        palette6.setBrush(QPalette.Inactive, QPalette.WindowText, brush4)
        palette6.setBrush(QPalette.Inactive, QPalette.Light, brush5)
        palette6.setBrush(QPalette.Inactive, QPalette.Dark, brush6)
        palette6.setBrush(QPalette.Inactive, QPalette.Text, brush4)
        palette6.setBrush(QPalette.Inactive, QPalette.BrightText, brush4)
        palette6.setBrush(QPalette.Inactive, QPalette.ButtonText, brush4)
        palette6.setBrush(QPalette.Inactive, QPalette.Base, brush7)
        palette6.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush8)
        palette6.setBrush(QPalette.Disabled, QPalette.WindowText, brush6)
        palette6.setBrush(QPalette.Disabled, QPalette.Light, brush5)
        palette6.setBrush(QPalette.Disabled, QPalette.Dark, brush6)
        palette6.setBrush(QPalette.Disabled, QPalette.Text, brush6)
        palette6.setBrush(QPalette.Disabled, QPalette.BrightText, brush4)
        palette6.setBrush(QPalette.Disabled, QPalette.ButtonText, brush6)
        palette6.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette6.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush8)
        self.sede.setPalette(palette6)
        font3 = QFont()
        font3.setFamilies([u"Century Gothic"])
        font3.setPointSize(9)
        self.sede.setFont(font3)
        self.nombrecliente = QLineEdit(self.centralwidget)
        self.nombrecliente.setObjectName(u"nombrecliente")
        self.nombrecliente.setGeometry(QRect(40, 290, 291, 31))
        palette7 = QPalette()
        brush9 = QBrush(QColor(92, 158, 194, 255))
        brush9.setStyle(Qt.SolidPattern)
        palette7.setBrush(QPalette.Active, QPalette.Base, brush9)
        palette7.setBrush(QPalette.Inactive, QPalette.Base, brush9)
        palette7.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        self.nombrecliente.setPalette(palette7)
        font4 = QFont()
        font4.setFamilies([u"Century Gothic"])
        font4.setPointSize(10)
        self.nombrecliente.setFont(font4)
        self.Correo = QLineEdit(self.centralwidget)
        self.Correo.setObjectName(u"Correo")
        self.Correo.setGeometry(QRect(40, 400, 281, 31))
        palette8 = QPalette()
        brush10 = QBrush(QColor(74, 155, 179, 255))
        brush10.setStyle(Qt.SolidPattern)
        palette8.setBrush(QPalette.Active, QPalette.Base, brush10)
        palette8.setBrush(QPalette.Inactive, QPalette.Base, brush10)
        palette8.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        self.Correo.setPalette(palette8)
        self.Correo.setFont(font4)
        self.dateTimeEdit = QDateTimeEdit(self.centralwidget)
        self.dateTimeEdit.setObjectName(u"dateTimeEdit")
        self.dateTimeEdit.setGeometry(QRect(410, 210, 271, 31))
        palette9 = QPalette()
        brush11 = QBrush(QColor(90, 182, 207, 255))
        brush11.setStyle(Qt.SolidPattern)
        palette9.setBrush(QPalette.Active, QPalette.Base, brush11)
        palette9.setBrush(QPalette.Inactive, QPalette.Base, brush11)
        palette9.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        self.dateTimeEdit.setPalette(palette9)
        self.pushButton_2 = QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(440, 310, 251, 51))
        palette10 = QPalette()
        brush12 = QBrush(QColor(120, 173, 202, 255))
        brush12.setStyle(Qt.SolidPattern)
        palette10.setBrush(QPalette.Active, QPalette.Base, brush12)
        palette10.setBrush(QPalette.Inactive, QPalette.Base, brush12)
        palette10.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        self.pushButton_2.setPalette(palette10)
        self.pushButton_2.setFont(font2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 26))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Formulario de citas", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Seleccionar sede:", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Horario disponible", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Nombre del cliente:", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Correo electronico:", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Salir", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"Enviar confirmaci\u00f3n", None))
    # retranslateUi

