# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ProcesarPagos.ui'
##
## Created by: Qt User Interface Compiler version 6.7.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QLabel, QLineEdit, QPushButton, QSizePolicy,
    QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(839, 616)
        self.frame = QFrame(Form)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(10, 10, 441, 591))
        self.frame.setStyleSheet(u"background-color: rgb(197, 198, 199);")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.lineEdit_2 = QLineEdit(self.frame)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(20, 120, 281, 31))
        self.lineEdit = QLineEdit(self.frame)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(20, 190, 281, 31))
        self.label = QLabel(self.frame)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 170, 101, 16))
        self.label.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_2 = QLabel(self.frame)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 100, 181, 16))
        self.label_2.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_3 = QLabel(self.frame)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(30, 340, 49, 16))
        self.label_3.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.comboBox = QComboBox(self.frame)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(30, 280, 72, 24))
        self.comboBox.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.comboBox_2 = QComboBox(self.frame)
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.setObjectName(u"comboBox_2")
        self.comboBox_2.setGeometry(QRect(140, 280, 72, 24))
        self.comboBox_2.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.lineEdit_3 = QLineEdit(self.frame)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(300, 280, 81, 24))
        self.lineEdit_4 = QLineEdit(self.frame)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setGeometry(QRect(30, 360, 281, 31))
        self.label_4 = QLabel(self.frame)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(110, 280, 21, 21))
        self.label_4.setStyleSheet(u"color: rgb(0, 0, 0);\n"
"font: 20pt \"Segoe UI\";")
        self.label_5 = QLabel(self.frame)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(20, 10, 271, 31))
        self.label_5.setStyleSheet(u"font: 16pt \"Segoe UI\";\n"
"color: rgb(0, 0, 0);")
        self.label_8 = QLabel(self.frame)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(260, 280, 31, 16))
        self.label_8.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_9 = QLabel(self.frame)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(30, 250, 71, 16))
        self.label_9.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.frame_3 = QFrame(self.frame)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(290, 10, 141, 61))
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.label_17 = QLabel(self.frame_3)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(10, 10, 121, 16))
        self.label_17.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_17.setWordWrap(True)
        self.pushButton_2 = QPushButton(self.frame_3)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(30, 30, 80, 24))
        self.pushButton_2.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.frame_4 = QFrame(self.frame)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setGeometry(QRect(10, 430, 401, 151))
        self.frame_4.setFrameShape(QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Raised)
        self.label_18 = QLabel(self.frame_4)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(10, 10, 49, 16))
        self.label_18.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_19 = QLabel(self.frame_4)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(260, 10, 131, 20))
        self.label_19.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_20 = QLabel(self.frame_4)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(10, 40, 49, 16))
        self.label_20.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_21 = QLabel(self.frame_4)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(260, 40, 121, 20))
        self.label_21.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_22 = QLabel(self.frame_4)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(10, 80, 81, 31))
        self.label_22.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_23 = QLabel(self.frame_4)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(260, 90, 121, 20))
        self.label_23.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.frame_2 = QFrame(Form)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(460, 10, 371, 591))
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.label_6 = QLabel(self.frame_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 70, 271, 31))
        self.label_6.setStyleSheet(u"font: 16pt \"Segoe UI\";\n"
"color: rgb(0, 0, 0);")
        self.checkBox = QCheckBox(self.frame_2)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(10, 30, 121, 22))
        self.label_7 = QLabel(self.frame_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 120, 321, 31))
        self.label_7.setScaledContents(True)
        self.label_7.setWordWrap(True)
        self.lineEdit_5 = QLineEdit(self.frame_2)
        self.lineEdit_5.setObjectName(u"lineEdit_5")
        self.lineEdit_5.setGeometry(QRect(10, 180, 121, 24))
        self.lineEdit_6 = QLineEdit(self.frame_2)
        self.lineEdit_6.setObjectName(u"lineEdit_6")
        self.lineEdit_6.setGeometry(QRect(150, 180, 181, 24))
        self.lineEdit_7 = QLineEdit(self.frame_2)
        self.lineEdit_7.setObjectName(u"lineEdit_7")
        self.lineEdit_7.setGeometry(QRect(20, 230, 331, 51))
        self.lineEdit_8 = QLineEdit(self.frame_2)
        self.lineEdit_8.setObjectName(u"lineEdit_8")
        self.lineEdit_8.setGeometry(QRect(40, 320, 121, 24))
        self.lineEdit_9 = QLineEdit(self.frame_2)
        self.lineEdit_9.setObjectName(u"lineEdit_9")
        self.lineEdit_9.setGeometry(QRect(200, 320, 121, 24))
        self.lineEdit_10 = QLineEdit(self.frame_2)
        self.lineEdit_10.setObjectName(u"lineEdit_10")
        self.lineEdit_10.setGeometry(QRect(40, 370, 121, 24))
        self.lineEdit_11 = QLineEdit(self.frame_2)
        self.lineEdit_11.setObjectName(u"lineEdit_11")
        self.lineEdit_11.setGeometry(QRect(30, 430, 271, 24))
        self.label_10 = QLabel(self.frame_2)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(40, 300, 49, 16))
        self.label_11 = QLabel(self.frame_2)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(200, 300, 49, 16))
        self.label_12 = QLabel(self.frame_2)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(40, 350, 81, 16))
        self.lineEdit_12 = QLineEdit(self.frame_2)
        self.lineEdit_12.setObjectName(u"lineEdit_12")
        self.lineEdit_12.setGeometry(QRect(200, 370, 121, 24))
        self.label_13 = QLabel(self.frame_2)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(200, 350, 81, 16))
        self.label_14 = QLabel(self.frame_2)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(20, 210, 91, 16))
        self.label_15 = QLabel(self.frame_2)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(30, 410, 111, 16))
        self.label_16 = QLabel(self.frame_2)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(30, 460, 291, 31))
        self.label_16.setWordWrap(True)
        self.pushButton = QPushButton(self.frame_2)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(30, 530, 141, 31))
        self.pushButton.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.label_24 = QLabel(self.frame_2)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(10, 160, 49, 16))
        self.label_25 = QLabel(self.frame_2)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(150, 160, 49, 16))

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.label.setText(QCoreApplication.translate("Form", u"Numero de Tarjeta", None))
        self.label_2.setText(QCoreApplication.translate("Form", u"Titular de la Tarjeta", None))
        self.label_3.setText(QCoreApplication.translate("Form", u"Correo", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("Form", u"01", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("Form", u"02", None))
        self.comboBox.setItemText(2, QCoreApplication.translate("Form", u"03", None))
        self.comboBox.setItemText(3, QCoreApplication.translate("Form", u"04", None))
        self.comboBox.setItemText(4, QCoreApplication.translate("Form", u"05", None))
        self.comboBox.setItemText(5, QCoreApplication.translate("Form", u"06", None))
        self.comboBox.setItemText(6, QCoreApplication.translate("Form", u"07", None))
        self.comboBox.setItemText(7, QCoreApplication.translate("Form", u"08", None))
        self.comboBox.setItemText(8, QCoreApplication.translate("Form", u"09", None))
        self.comboBox.setItemText(9, QCoreApplication.translate("Form", u"10", None))
        self.comboBox.setItemText(10, QCoreApplication.translate("Form", u"11", None))
        self.comboBox.setItemText(11, QCoreApplication.translate("Form", u"12", None))

        self.comboBox_2.setItemText(0, QCoreApplication.translate("Form", u"24", None))
        self.comboBox_2.setItemText(1, QCoreApplication.translate("Form", u"25", None))
        self.comboBox_2.setItemText(2, QCoreApplication.translate("Form", u"26", None))
        self.comboBox_2.setItemText(3, QCoreApplication.translate("Form", u"27", None))
        self.comboBox_2.setItemText(4, QCoreApplication.translate("Form", u"28", None))
        self.comboBox_2.setItemText(5, QCoreApplication.translate("Form", u"29", None))
        self.comboBox_2.setItemText(6, QCoreApplication.translate("Form", u"30", None))
        self.comboBox_2.setItemText(7, QCoreApplication.translate("Form", u"31", None))
        self.comboBox_2.setItemText(8, QCoreApplication.translate("Form", u"32", None))
        self.comboBox_2.setItemText(9, QCoreApplication.translate("Form", u"33", None))
        self.comboBox_2.setItemText(10, QCoreApplication.translate("Form", u"34", None))
        self.comboBox_2.setItemText(11, QCoreApplication.translate("Form", u"35", None))
        self.comboBox_2.setItemText(12, QCoreApplication.translate("Form", u"36", None))
        self.comboBox_2.setItemText(13, QCoreApplication.translate("Form", u"37", None))
        self.comboBox_2.setItemText(14, QCoreApplication.translate("Form", u"38", None))
        self.comboBox_2.setItemText(15, QCoreApplication.translate("Form", u"39", None))
        self.comboBox_2.setItemText(16, QCoreApplication.translate("Form", u"40", None))
        self.comboBox_2.setItemText(17, QCoreApplication.translate("Form", u"41", None))
        self.comboBox_2.setItemText(18, QCoreApplication.translate("Form", u"42", None))
        self.comboBox_2.setItemText(19, QCoreApplication.translate("Form", u"43", None))
        self.comboBox_2.setItemText(20, QCoreApplication.translate("Form", u"44", None))
        self.comboBox_2.setItemText(21, QCoreApplication.translate("Form", u"45", None))
        self.comboBox_2.setItemText(22, QCoreApplication.translate("Form", u"46", None))
        self.comboBox_2.setItemText(23, QCoreApplication.translate("Form", u"47", None))
        self.comboBox_2.setItemText(24, QCoreApplication.translate("Form", u"48", None))
        self.comboBox_2.setItemText(25, QCoreApplication.translate("Form", u"49", None))
        self.comboBox_2.setItemText(26, QCoreApplication.translate("Form", u"50", None))

        self.label_4.setText(QCoreApplication.translate("Form", u"/", None))
        self.label_5.setText(QCoreApplication.translate("Form", u"Pago con Tarjeta de Credito", None))
        self.label_8.setText(QCoreApplication.translate("Form", u"CCV", None))
        self.label_9.setText(QCoreApplication.translate("Form", u"Vencimiento", None))
        self.label_17.setText(QCoreApplication.translate("Form", u"Otros Medios de Pago ", None))
        self.pushButton_2.setText(QCoreApplication.translate("Form", u"Click Here", None))
        self.label_18.setText(QCoreApplication.translate("Form", u"Subtotal:", None))
        self.label_19.setText(QCoreApplication.translate("Form", u"0", None))
        self.label_20.setText(QCoreApplication.translate("Form", u"Env\u00edo:", None))
        self.label_21.setText(QCoreApplication.translate("Form", u"0", None))
        self.label_22.setText(QCoreApplication.translate("Form", u"TOTAL:", None))
        self.label_23.setText(QCoreApplication.translate("Form", u"0", None))
        self.label_6.setText(QCoreApplication.translate("Form", u"Entrega", None))
        self.checkBox.setText(QCoreApplication.translate("Form", u"Retiro en Tienda", None))
        self.label_7.setText(QCoreApplication.translate("Form", u"Todos los envios tienen un adicional de 4500", None))
        self.label_10.setText(QCoreApplication.translate("Form", u"Provincia", None))
        self.label_11.setText(QCoreApplication.translate("Form", u"Canton", None))
        self.label_12.setText(QCoreApplication.translate("Form", u"Distrito", None))
        self.label_13.setText(QCoreApplication.translate("Form", u"Codigo Postal", None))
        self.label_14.setText(QCoreApplication.translate("Form", u"Direcci\u00f3n Exacta", None))
        self.label_15.setText(QCoreApplication.translate("Form", u"Numero de telefono", None))
        self.label_16.setText(QCoreApplication.translate("Form", u"Correos de Costa Rica se comunicar\u00e1 con su persona por este medio", None))
        self.pushButton.setText(QCoreApplication.translate("Form", u"Finalizar Transacci\u00f3n", None))
        self.label_24.setText(QCoreApplication.translate("Form", u"Nombre", None))
        self.label_25.setText(QCoreApplication.translate("Form", u"Apellidos", None))
    # retranslateUi

