# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Registro_Servicios.ui'
##
## Created by: Qt User Interface Compiler version 6.7.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDateEdit, QLabel, QLineEdit,
    QMainWindow, QMenuBar, QPushButton, QSizePolicy,
    QStatusBar, QTextEdit, QTimeEdit, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1092, 756)
        palette = QPalette()
        brush = QBrush(QColor(76, 173, 202, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush)
        brush1 = QBrush(QColor(88, 191, 211, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        MainWindow.setPalette(palette)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(40, 90, 91, 51))
        palette1 = QPalette()
        brush2 = QBrush(QColor(253, 253, 253, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        brush3 = QBrush(QColor(247, 247, 247, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush3)
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Text, brush3)
        brush4 = QBrush(QColor(120, 120, 120, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        self.label.setPalette(palette1)
        font = QFont()
        font.setFamilies([u"Century Gothic"])
        font.setPointSize(14)
        self.label.setFont(font)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 10, 531, 51))
        palette2 = QPalette()
        brush5 = QBrush(QColor(248, 248, 248, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush5)
        brush6 = QBrush(QColor(249, 249, 249, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.Text, brush6)
        brush7 = QBrush(QColor(246, 246, 253, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.ButtonText, brush7)
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush5)
        palette2.setBrush(QPalette.Inactive, QPalette.Text, brush6)
        palette2.setBrush(QPalette.Inactive, QPalette.ButtonText, brush7)
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette2.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette2.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        self.label_2.setPalette(palette2)
        font1 = QFont()
        font1.setFamilies([u"Century Gothic"])
        font1.setPointSize(18)
        font1.setBold(False)
        self.label_2.setFont(font1)
        self.fecha = QDateEdit(self.centralwidget)
        self.fecha.setObjectName(u"fecha")
        self.fecha.setGeometry(QRect(120, 100, 211, 31))
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(370, 90, 91, 51))
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette3.setBrush(QPalette.Active, QPalette.Text, brush3)
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette3.setBrush(QPalette.Inactive, QPalette.Text, brush3)
        palette3.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette3.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        self.label_3.setPalette(palette3)
        self.label_3.setFont(font)
        self.hora = QTimeEdit(self.centralwidget)
        self.hora.setObjectName(u"hora")
        self.hora.setGeometry(QRect(470, 100, 231, 31))
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(40, 150, 151, 51))
        palette4 = QPalette()
        palette4.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette4.setBrush(QPalette.Active, QPalette.Text, brush3)
        palette4.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette4.setBrush(QPalette.Inactive, QPalette.Text, brush3)
        palette4.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette4.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        self.label_4.setPalette(palette4)
        self.label_4.setFont(font)
        self.veterinarionombre = QLineEdit(self.centralwidget)
        self.veterinarionombre.setObjectName(u"veterinarionombre")
        self.veterinarionombre.setGeometry(QRect(180, 160, 521, 31))
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(40, 200, 151, 51))
        palette5 = QPalette()
        palette5.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette5.setBrush(QPalette.Active, QPalette.Text, brush3)
        palette5.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette5.setBrush(QPalette.Inactive, QPalette.Text, brush3)
        palette5.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette5.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        self.label_5.setPalette(palette5)
        self.label_5.setFont(font)
        self.propietarionombre = QLineEdit(self.centralwidget)
        self.propietarionombre.setObjectName(u"propietarionombre")
        self.propietarionombre.setGeometry(QRect(180, 210, 521, 31))
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(40, 240, 191, 51))
        palette6 = QPalette()
        palette6.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette6.setBrush(QPalette.Active, QPalette.Text, brush3)
        palette6.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette6.setBrush(QPalette.Inactive, QPalette.Text, brush3)
        palette6.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette6.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        self.label_6.setPalette(palette6)
        self.label_6.setFont(font)
        self.tipodeservicio = QLineEdit(self.centralwidget)
        self.tipodeservicio.setObjectName(u"tipodeservicio")
        self.tipodeservicio.setGeometry(QRect(230, 250, 471, 31))
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(40, 310, 171, 51))
        palette7 = QPalette()
        palette7.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette7.setBrush(QPalette.Active, QPalette.Text, brush3)
        palette7.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette7.setBrush(QPalette.Inactive, QPalette.Text, brush3)
        palette7.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette7.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        self.label_7.setPalette(palette7)
        self.label_7.setFont(font)
        self.comentario = QTextEdit(self.centralwidget)
        self.comentario.setObjectName(u"comentario")
        self.comentario.setGeometry(QRect(200, 330, 311, 111))
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(220, 450, 201, 51))
        palette8 = QPalette()
        palette8.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette8.setBrush(QPalette.Active, QPalette.Text, brush3)
        palette8.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette8.setBrush(QPalette.Inactive, QPalette.Text, brush3)
        palette8.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette8.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        self.label_8.setPalette(palette8)
        self.label_8.setFont(font)
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(530, 310, 121, 51))
        palette9 = QPalette()
        palette9.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette9.setBrush(QPalette.Active, QPalette.Text, brush3)
        palette9.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette9.setBrush(QPalette.Inactive, QPalette.Text, brush3)
        palette9.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette9.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        self.label_9.setPalette(palette9)
        self.label_9.setFont(font)
        self.archivos = QTextEdit(self.centralwidget)
        self.archivos.setObjectName(u"archivos")
        self.archivos.setGeometry(QRect(650, 330, 341, 111))
        self.medicamentos = QTextEdit(self.centralwidget)
        self.medicamentos.setObjectName(u"medicamentos")
        self.medicamentos.setGeometry(QRect(40, 500, 501, 171))
        self.btn_agregar = QPushButton(self.centralwidget)
        self.btn_agregar.setObjectName(u"btn_agregar")
        self.btn_agregar.setGeometry(QRect(850, 90, 181, 61))
        font2 = QFont()
        font2.setFamilies([u"Century Gothic"])
        font2.setPointSize(10)
        font2.setBold(True)
        self.btn_agregar.setFont(font2)
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(770, 460, 101, 51))
        palette10 = QPalette()
        palette10.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette10.setBrush(QPalette.Active, QPalette.Text, brush3)
        palette10.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette10.setBrush(QPalette.Inactive, QPalette.Text, brush3)
        palette10.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette10.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        self.label_10.setPalette(palette10)
        self.label_10.setFont(font)
        self.historial = QTextEdit(self.centralwidget)
        self.historial.setObjectName(u"historial")
        self.historial.setGeometry(QRect(600, 500, 451, 171))
        self.btn_salir = QPushButton(self.centralwidget)
        self.btn_salir.setObjectName(u"btn_salir")
        self.btn_salir.setGeometry(QRect(850, 180, 181, 61))
        self.btn_salir.setFont(font2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1092, 26))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Fecha:", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Registro de Servicios Veterinarios", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Hora:", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Veterinario:", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Propietario:", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Tipo de servicio:", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Comentarios:", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Medicamentos:", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Archivos:", None))
        self.btn_agregar.setText(QCoreApplication.translate("MainWindow", u"Agregar", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Historial:", None))
        self.btn_salir.setText(QCoreApplication.translate("MainWindow", u"Salir", None))
    # retranslateUi

