# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Ventana5.ui'
##
## Created by: Qt User Interface Compiler version 6.7.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QMainWindow, QMdiArea,
    QMenuBar, QPushButton, QSizePolicy, QStatusBar,
    QWidget)
import Imagenes_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1115, 808)
        MainWindow.setStyleSheet(u"QWidget#centralwidget{background-color: qlineargradient(spread:pad, x1:0.239, y1:0.295455, x2:1, y2:1, stop:0.308458 rgba(26, 72, 91, 255), stop:1 rgba(255, 255, 255, 255))};\n"
"")
        MainWindow.setAnimated(True)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(110, 0, 561, 101))
        self.label.setStyleSheet(u"font: 36pt \"MS Shell Dlg 2\";\n"
"color:red;")
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(-40, 0, 181, 111))
        self.label_6.setStyleSheet(u"image: url(:/login/Imagen2.jpg)")
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(120, 260, 321, 51))
        self.pushButton.setStyleSheet(u"font: 16pt \"MS Shell Dlg 2\";")
        self.pushButton_2 = QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(110, 150, 241, 51))
        self.pushButton_2.setStyleSheet(u"font: 16pt \"MS Shell Dlg 2\";")
        self.pushButton_3 = QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(900, 190, 221, 51))
        self.pushButton_3.setStyleSheet(u"font: 16pt \"MS Shell Dlg 2\";")
        self.pushButton_4 = QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(150, 530, 251, 51))
        self.pushButton_4.setStyleSheet(u"font: 16pt \"MS Shell Dlg 2\";")
        self.pushButton_5 = QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(870, 700, 251, 51))
        self.pushButton_5.setStyleSheet(u"font: 16pt \"MS Shell Dlg 2\";\n"
"color: red;")
        self.pushButton_6 = QPushButton(self.centralwidget)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(140, 390, 321, 51))
        self.pushButton_6.setStyleSheet(u"font: 16pt \"MS Shell Dlg 2\";")
        self.pushButton_7 = QPushButton(self.centralwidget)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(160, 660, 251, 51))
        self.pushButton_7.setStyleSheet(u"font: 16pt \"MS Shell Dlg 2\";")
        self.pushButton_8 = QPushButton(self.centralwidget)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(900, 0, 221, 51))
        self.pushButton_8.setStyleSheet(u"font: 16pt \"MS Shell Dlg 2\";")
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(0, 120, 121, 111))
        self.label_3.setStyleSheet(u"image: url(:/login/Imagen3.png)")
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 230, 111, 111))
        self.label_4.setStyleSheet(u"image: url(:/login/Imagen4.png)")
        self.pushButton_9 = QPushButton(self.centralwidget)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setGeometry(QRect(900, 260, 221, 51))
        self.pushButton_9.setStyleSheet(u"font: 16pt \"MS Shell Dlg 2\";")
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(-90, 300, 391, 261))
        self.label_5.setStyleSheet(u"image: url(:/login/Imagen 6.png)\n"
"\n"
"")
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 490, 141, 111))
        self.label_7.setStyleSheet(u"image: url(:/login/Imagen5.png)")
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 620, 121, 111))
        self.label_8.setStyleSheet(u"image:  url(:/login/Imagen1.png)")
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(900, 0, 61, 51))
        self.label_9.setStyleSheet(u"image: url(:/login/Imagen7.png)")
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(730, 190, 191, 121))
        self.label_10.setStyleSheet(u"image: url(:/login/Imagen8.png)")
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(520, 90, 581, 51))
        self.mdiArea = QMdiArea(self.centralwidget)
        self.mdiArea.setObjectName(u"mdiArea")
        self.mdiArea.setGeometry(QRect(130, 140, 261, 71))
        self.mdiArea_2 = QMdiArea(self.centralwidget)
        self.mdiArea_2.setObjectName(u"mdiArea_2")
        self.mdiArea_2.setGeometry(QRect(190, 250, 261, 71))
        self.mdiArea_3 = QMdiArea(self.centralwidget)
        self.mdiArea_3.setObjectName(u"mdiArea_3")
        self.mdiArea_3.setGeometry(QRect(220, 380, 261, 71))
        self.mdiArea_4 = QMdiArea(self.centralwidget)
        self.mdiArea_4.setObjectName(u"mdiArea_4")
        self.mdiArea_4.setGeometry(QRect(170, 520, 261, 71))
        self.mdiArea_5 = QMdiArea(self.centralwidget)
        self.mdiArea_5.setObjectName(u"mdiArea_5")
        self.mdiArea_5.setGeometry(QRect(180, 650, 261, 71))
        self.mdiArea_6 = QMdiArea(self.centralwidget)
        self.mdiArea_6.setObjectName(u"mdiArea_6")
        self.mdiArea_6.setGeometry(QRect(890, 180, 261, 71))
        self.mdiArea_7 = QMdiArea(self.centralwidget)
        self.mdiArea_7.setObjectName(u"mdiArea_7")
        self.mdiArea_7.setGeometry(QRect(890, 260, 261, 61))
        self.mdiArea_8 = QMdiArea(self.centralwidget)
        self.mdiArea_8.setObjectName(u"mdiArea_8")
        self.mdiArea_8.setGeometry(QRect(960, -10, 261, 71))
        MainWindow.setCentralWidget(self.centralwidget)
        self.mdiArea_8.raise_()
        self.mdiArea_7.raise_()
        self.mdiArea_6.raise_()
        self.mdiArea_5.raise_()
        self.mdiArea_4.raise_()
        self.mdiArea_3.raise_()
        self.mdiArea_2.raise_()
        self.mdiArea.raise_()
        self.label.raise_()
        self.label_6.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.pushButton_5.raise_()
        self.pushButton_6.raise_()
        self.pushButton_7.raise_()
        self.pushButton_8.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.pushButton_9.raise_()
        self.label_5.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_2.raise_()
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1115, 26))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Veterinaria MiPet", None))
        self.label_6.setText("")
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Perfil Propietario", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"Historial Cl\u00ednico", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"Historial de Citas", None))
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u"Tienda en l\u00ednea", None))
        self.pushButton_5.setText(QCoreApplication.translate("MainWindow", u"Salir", None))
        self.pushButton_6.setText(QCoreApplication.translate("MainWindow", u"Perfil Mascotas", None))
        self.pushButton_7.setText(QCoreApplication.translate("MainWindow", u"Facturaciones ", None))
        self.pushButton_8.setText(QCoreApplication.translate("MainWindow", u"Llamar", None))
        self.label_3.setText("")
        self.label_4.setText("")
        self.pushButton_9.setText(QCoreApplication.translate("MainWindow", u"Solicitar Citas", None))
        self.label_5.setText("")
        self.label_7.setText("")
        self.label_8.setText("")
        self.label_9.setText("")
        self.label_10.setText("")
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:24pt; font-weight:600; color:#ffaa7f;\">Bienvenido client@!</span></p></body></html>", None))
    # retranslateUi

